name: Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Angular project
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
    
      - name: Compile client code
          run: |
          npm ci
          npm run build -- --configuration=prod
          rm -f dist/*.map
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ${{ inputs.ng_directory }}/dist
            ${{ inputs.ng_directory }}/src/configs
          retention-days: 1

      - name: CDK deploy
        uses: scottbrenner/aws-cdk-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
