name: Deployment

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

env:
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
jobs:
  build:
    name: Deploy Angular project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: Compile client code
        run: |
          cd ./cdk
          npm ci
          cd ..

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2.1.1
        with:
          cdk_subcommand: "deploy"
          cdk_stack: "frontend-riskRoller"
          cdk_args: "--require-approval never"
          working_dir: "./cdk"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
