name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
jobs:
  build:
    name: Build Angular project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: Compile client code
        run: |
          npm ci
          npm run build
          rm -f dist/*.map
          cd ./cdk
          npm ci
          cd ..

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ${{ inputs.ng_directory }}/dist
            ${{ inputs.ng_directory }}/src/configs
          retention-days: 1

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - run: yarn install

      - name: Synth stack
        run: yarn --cwd cdk cdk synth

      - name: Deploy stack
        run: yarn --cwd cdk cdk deploy --require-approval never
      # - name: cdk bootstrap
      #   uses: youyo/aws-cdk-github-actions@v2.1.1
      #   with:
      #     cdk_subcommand: "bootstrap"
      #     cdk_stack: "aws:// ${{ secrets.AWS_ACCOUNT }}/us-east-1"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: "us-east-1"

      # - name: cdk synth
      #   uses: youyo/aws-cdk-github-actions@v2.1.1
      #   with:
      #     cdk_subcommand: "synth"
      #     working_dir: "./cdk"
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: "us-east-1"

      # - name: cdk deploy
      #   uses: youyo/aws-cdk-github-actions@v2.1.1
      #   with:
      #     cdk_subcommand: "deploy"
      #     cdk_stack: "frontend-riskRoller"
      #     cdk_args: "--require-approval never"
      #     working_dir: "./cdk"
      #     actions_comment: false
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: "us-east-1"
